//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engine.Operations.ResourcesOps
{


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApiAddress {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiAddress() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Engine.Operations.ResourcesOps.ApiAddress", typeof(ApiAddress).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.kometsales.com/api/box.code.change.
        /// </summary>
        internal static string KometBoxCodeChange {
            get {
                return ResourceManager.GetString("KometBoxCodeChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.kometsales.com/api/boxtype.list.
        /// </summary>
        internal static string KometBoxTypeList {
            get {
                return ResourceManager.GetString("KometBoxTypeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.kometsales.com/api/customer.list.
        /// </summary>
        internal static string KometCustomerList {
            get {
                return ResourceManager.GetString("KometCustomerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.kometsales.com/api/customer.shipto.list.
        /// </summary>
        internal static string KometCustomerShipToList {
            get {
                return ResourceManager.GetString("KometCustomerShipToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.kometsales.com/api/inventory.add.
        /// </summary>
        internal static string KometInventoryAdd {
            get {
                return ResourceManager.GetString("KometInventoryAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.kometsales.com/api/invoice.details.list.
        /// </summary>
        internal static string KometInvoiceDetailList {
            get {
                return ResourceManager.GetString("KometInvoiceDetailList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.kometsales.com/api/invoice.mark.sync.
        /// </summary>
        internal static string KometInvoiceIntegrate {
            get {
                return ResourceManager.GetString("KometInvoiceIntegrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.kometsales.com/api/invoice.update.
        /// </summary>
        internal static string KometInvoiceUpdate {
            get {
                return ResourceManager.GetString("KometInvoiceUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.kometsales.com/api/location.list.
        /// </summary>
        internal static string KometLocationList {
            get {
                return ResourceManager.GetString("KometLocationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.kometsales.com/api/login.
        /// </summary>
        internal static string KometLogin {
            get {
                return ResourceManager.GetString("KometLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.kometsales.com/api/purchase.order.item.reference.update.
        /// </summary>
        internal static string KometPOUpdate {
            get {
                return ResourceManager.GetString("KometPOUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.kometsales.com/api/prebook.details.list.
        /// </summary>
        internal static string KometPrebookList {
            get {
                return ResourceManager.GetString("KometPrebookList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.kometsales.com/api/product.list.
        /// </summary>
        internal static string KometProductList {
            get {
                return ResourceManager.GetString("KometProductList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.kometsales.com/api/purchase.order.list.
        /// </summary>
        internal static string KometPurchaseDetailList {
            get {
                return ResourceManager.GetString("KometPurchaseDetailList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.kometsales.com/api/standing.order.list.
        /// </summary>
        internal static string KometStandingOrderList {
            get {
                return ResourceManager.GetString("KometStandingOrderList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.kometsales.com/api/purchase.order.va.details.list.
        /// </summary>
        internal static string KometVendorAvailabilityList {
            get {
                return ResourceManager.GetString("KometVendorAvailabilityList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.kometsales.com/api/vendor.list.
        /// </summary>
        internal static string KometVendorList {
            get {
                return ResourceManager.GetString("KometVendorList", resourceCulture);
            }
        }
    }
}
