//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engine.Operations.ResourcesOps {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Queries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Queries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Engine.Operations.ResourcesOps.Queries", typeof(Queries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_KS_BoxCodesSwap.
        /// </summary>
        internal static string BoxCodesToChange {
            get {
                return ResourceManager.GetString("BoxCodesToChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_KS_BoxCodeSwapActualizar.
        /// </summary>
        internal static string BoxCodesToChangeUpdate {
            get {
                return ResourceManager.GetString("BoxCodesToChangeUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_KS_BoxTypeInsertar.
        /// </summary>
        internal static string BoxTypeInsert {
            get {
                return ResourceManager.GetString("BoxTypeInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_KS_BoxTypeActualizar.
        /// </summary>
        internal static string BoxTypeUpdate {
            get {
                return ResourceManager.GetString("BoxTypeUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_KS_InvoiceSpecificUpdate.
        /// </summary>
        internal static string ChangeSpecificInvoiceStatus {
            get {
                return ResourceManager.GetString("ChangeSpecificInvoiceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_KS_Invoice_Initialize.
        /// </summary>
        internal static string CleanInvoiceWorkspace {
            get {
                return ResourceManager.GetString("CleanInvoiceWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_KS_PO_Initialize.
        /// </summary>
        internal static string CleanPOWorkspace {
            get {
                return ResourceManager.GetString("CleanPOWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_KS_PO_initializeWithNumber.
        /// </summary>
        internal static string CleanPOWorkspaceA {
            get {
                return ResourceManager.GetString("CleanPOWorkspaceA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_KS_SO_Initialize.
        /// </summary>
        internal static string CleanSOWorkspace {
            get {
                return ResourceManager.GetString("CleanSOWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_KS_CustomerInsertar.
        /// </summary>
        internal static string CustomerInsert {
            get {
                return ResourceManager.GetString("CustomerInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_KS_CustomerActualizar.
        /// </summary>
        internal static string CustomerUpdate {
            get {
                return ResourceManager.GetString("CustomerUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_KS_Invoice_GetInformation.
        /// </summary>
        internal static string GetInvoiceInformation {
            get {
                return ResourceManager.GetString("GetInvoiceInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_PS_PurchaseVsPedi.
        /// </summary>
        internal static string GetPackingBoxes {
            get {
                return ResourceManager.GetString("GetPackingBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_KS_Invoice_GetTransfer.
        /// </summary>
        internal static string GetTransferInvoice {
            get {
                return ResourceManager.GetString("GetTransferInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_KS_InventoryOutDetails.
        /// </summary>
        internal static string InventoryChildSelect {
            get {
                return ResourceManager.GetString("InventoryChildSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_KS_InventoryOut.
        /// </summary>
        internal static string InventorySelect {
            get {
                return ResourceManager.GetString("InventorySelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_KS_InventoryActualizar.
        /// </summary>
        internal static string InventoryUpdate {
            get {
                return ResourceManager.GetString("InventoryUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_KS_inventoryWithErrors.
        /// </summary>
        internal static string InventoryWithErrors {
            get {
                return ResourceManager.GetString("InventoryWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_KS_Invoice_ETL.
        /// </summary>
        internal static string InvoiceEtl {
            get {
                return ResourceManager.GetString("InvoiceEtl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_KS_LocationInsertar.
        /// </summary>
        internal static string LocationInsert {
            get {
                return ResourceManager.GetString("LocationInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_KS_LocationActualizar.
        /// </summary>
        internal static string LocationUpdate {
            get {
                return ResourceManager.GetString("LocationUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_PS_PedidosFacturados.
        /// </summary>
        internal static string PackingsWithBills {
            get {
                return ResourceManager.GetString("PackingsWithBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_KS_PO_ETL.
        /// </summary>
        internal static string POEtl {
            get {
                return ResourceManager.GetString("POEtl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_KS_PO_StandarizeInfo.
        /// </summary>
        internal static string POStandarizeInfo {
            get {
                return ResourceManager.GetString("POStandarizeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_KS_PrebookInsertar.
        /// </summary>
        internal static string PrebookInsert {
            get {
                return ResourceManager.GetString("PrebookInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_KS_GetInvoices.
        /// </summary>
        internal static string PreloadInvoices {
            get {
                return ResourceManager.GetString("PreloadInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_KS_ProductInsertar.
        /// </summary>
        internal static string ProductInsert {
            get {
                return ResourceManager.GetString("ProductInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_PS_ProductionETL.
        /// </summary>
        internal static string ProductionEtl {
            get {
                return ResourceManager.GetString("ProductionEtl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_KS_ProductActualizar.
        /// </summary>
        internal static string ProductUpdate {
            get {
                return ResourceManager.GetString("ProductUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_KS_CustomerToMySql.
        /// </summary>
        internal static string SendCustomerToDw {
            get {
                return ResourceManager.GetString("SendCustomerToDw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_KS_InvoiceToMySql.
        /// </summary>
        internal static string SendInvoicesToDw {
            get {
                return ResourceManager.GetString("SendInvoicesToDw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_ProductionToMySql.
        /// </summary>
        internal static string SendProductionToDw {
            get {
                return ResourceManager.GetString("SendProductionToDw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_KS_ShipTo_ETL.
        /// </summary>
        internal static string ShipToEtl {
            get {
                return ResourceManager.GetString("ShipToEtl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_KS_ShipTo_Initialize.
        /// </summary>
        internal static string ShipToInitialize {
            get {
                return ResourceManager.GetString("ShipToInitialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_KS_SodETL.
        /// </summary>
        internal static string SodEtl {
            get {
                return ResourceManager.GetString("SodEtl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_KS_Sod_Generate.
        /// </summary>
        internal static string SodGenerator {
            get {
                return ResourceManager.GetString("SodGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_KS_SO_ETL.
        /// </summary>
        internal static string StandingOrderEtl {
            get {
                return ResourceManager.GetString("StandingOrderEtl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_KS_VendorAvailability_ETL.
        /// </summary>
        internal static string VAEtl {
            get {
                return ResourceManager.GetString("VAEtl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_KS_VA_Initialize.
        /// </summary>
        internal static string VAInitializeProcess {
            get {
                return ResourceManager.GetString("VAInitializeProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_KS_VendorInsertar.
        /// </summary>
        internal static string VendorInsert {
            get {
                return ResourceManager.GetString("VendorInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_KS_VendorActualizar.
        /// </summary>
        internal static string VendorUpdate {
            get {
                return ResourceManager.GetString("VendorUpdate", resourceCulture);
            }
        }
    }
}
